import sys
import pygame
from settings import Settings
from ship import Ship


class AlienInvasion:
    """General class dedicated to managing the resources and the way the game works."""

    def __init__(self):
        """Initialize game and create resources."""

        pygame.init()
        self.settings = Settings()

        self.screen = pygame.display.set_mode((self.settings.screen_width, self.settings.screen_height))
        pygame.display.set_caption("Alien Invasion")

        self.ship = Ship(self)

    def run_game(self):
        """Start main loop of the program"""

        print(pygame.K_RIGHT)

        while True:
            self._check_events()
            self.ship.update()
            self._update_screen()

    def _check_events(self):
        """Reaction for events generated by keyboard and mouse"""
        # Waiting for input from a user
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_RIGHT:
                    #Moving the ship to the right side
                    self.ship.moving_right = True
                elif event.key == pygame.K_LEFT:
                    self.ship.moving_left = True

            elif event.type == pygame.KEYUP:
                if event.key == pygame.K_RIGHT:
                    self.ship.moving_right = False
                elif event.key == pygame.K_LEFT:
                    self.ship.moving_left = False

    def _update_screen(self):
        """updating the images on the screen and going to a new screen"""
        # Refresh screen after each iteration of the loop
        self.screen.fill(self.settings.bg_color)
        self.ship.blitme()

        # Displaying the last modified screen
        pygame.display.flip()


if __name__ == '__main__':
    #Creating a copy of the game and launching it
    ai = AlienInvasion()
    ai.run_game()


